build: add node v19
Node v19.0.0 has been released.
https://nodejs.org/en/blog/release/v19.0.0/

This PR adds the v19 matrix and fixes the following tests failure when using v19.0.0.

```console
% node -v
v19.0.0
% npx mocha tests/lib/shared/runtime-info.js
(snip)

1) RuntimeInfo
     environment()
       log and throw an error when checking for local ESLint version when returned output of command is malformed:

    AssertionError: expected [Function environment] to throw error including 'Unexpected token T in JSON at positio…' but got 'Unexpected token \'T\', "This is not …'
    + expected - actual

    -Unexpected token 'T', "This is not JSON" is not valid JSON
    +Unexpected token T in JSON at position 0

    at Context.<anonymous> (tests/lib/shared/runtime-info.js:209:20)
    at process.processImmediate (node:internal/timers:471:21)

2) RuntimeInfo
     environment()
       log and throw an error when checking for global ESLint version when returned output of command is malformed:

    AssertionError: expected [Function environment] to throw error including 'Unexpected token T in JSON at positio…' but got 'Unexpected token \'T\', "This is not …'
    + expected - actual

    -Unexpected token 'T', "This is not JSON" is not valid JSON
    +Unexpected token T in JSON at position 0

    at Context.<anonymous> (tests/lib/shared/runtime-info.js:217:20)
    at process.processImmediate (node:internal/timers:471:21)
```

This patch uses regexp to match both messages because the message has changed in v19.0.0.