Replace `context.sourceCode` with `context.getSourceCode()` in no-warning-comments.js
For the rule `no-warning-comments` the variable `sourceCode` was undefined and resulting in the following error:

```
$ yarn lint           

yarn run v1.9.4
$ getk run lint-es '**/*.{js,jsx,ts,tsx}' --ignore-path .gitignore

Oops! Something went wrong! :(

ESLint: 8.43.0

TypeError: Cannot read properties of undefined (reading 'getAllComments')
Occurred while linting /Users/shermam/Projects/format-location/.eslintrc.js:1
Rule: "unicorn/expiring-todo-comments"
    at Object.Program (/Users/shermam/Projects/format-location/node_modules/eslint/lib/rules/no-warning-comments.js:193:45)
    at Program (/Users/shermam/Projects/format-location/node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js:511:10)
    at /Users/shermam/Projects/format-location/node_modules/eslint-plugin-unicorn/rules/utils/rule.js:39:18
    at ruleErrorHandler (/Users/shermam/Projects/format-location/node_modules/eslint/lib/linter/linter.js:1050:28)
    at /Users/shermam/Projects/format-location/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/shermam/Projects/format-location/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/shermam/Projects/format-location/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/shermam/Projects/format-location/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/Users/shermam/Projects/format-location/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/Users/shermam/Projects/format-location/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at /Users/shermam/Projects/format-location/node_modules/eslint/lib/linter/linter.js:1085:32
    at Array.forEach (<anonymous>)
    at runRules (/Users/shermam/Projects/format-location/node_modules/eslint/lib/linter/linter.js:1080:15)
    at Linter._verifyWithoutProcessors (/Users/shermam/Projects/format-location/node_modules/eslint/lib/linter/linter.js:1330:31)
    at Linter._verifyWithoutProcessors (/Users/shermam/Projects/format-location/node_modules/eslint-plugin-eslint-comments/lib/utils/patch.js:166:36)
    at Linter._verifyWithConfigArray (/Users/shermam/Projects/format-location/node_modules/eslint/lib/linter/linter.js:1706:21)
    at Linter.verify (/Users/shermam/Projects/format-location/node_modules/eslint/lib/linter/linter.js:1412:65)
    at Linter.verifyAndFix (/Users/shermam/Projects/format-location/node_modules/eslint/lib/linter/linter.js:1967:29)
    at verifyText (/Users/shermam/Projects/format-location/node_modules/eslint/lib/cli-engine/cli-engine.js:245:48)
    at CLIEngine.executeOnFiles (/Users/shermam/Projects/format-location/node_modules/eslint/lib/cli-engine/cli-engine.js:825:28)
    at ESLint.lintFiles (/Users/shermam/Projects/format-location/node_modules/eslint/lib/eslint/eslint.js:551:23)
    at Object.execute (/Users/shermam/Projects/format-location/node_modules/eslint/lib/cli.js:391:36)
    at async main (/Users/shermam/Projects/format-location/node_modules/eslint/bin/eslint.js:135:24)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This change set updates the code to use `context.getSourceCode()` instead of `context.sourceCode` which is no longer defined.