feat: Add support for TS config files (#18134)
* Initial working implementation of TS config files

* Simplify implementation

* Use typescript's `transpile()` instead of `tsx` to avoid side effects

* Remove unnecessary nullish coalescing

* Use `jiti` instead of TypeScript

* Add missing section related to `importedConfigFileModificationTime`

* Enable `esmResolve` for `jiti`

* Make `jiti` an optional peer dependency

* Throw an error if `jiti` is not installed

* Add `jiti` to `ignoreDependencies` in `knip.jsonc`

* Fix broken unit tests caused by stubbed `process.version`

Co-authored-by: Anthony Fu <anthonyfu117@hotmail.com>

* Prioritize JavaScript config files over TypeScript config files

* Add some basic tests for loading TS config files

* Fix minor type issues in JSDocs

* Partially Inline the `FlatConfig` type from `@types/eslint` to reuse

- This is not only done to reduce some potential redundancy down the line, but to ensure that TS config files are able to handle `type` imports as that is something most people are likely going to do.

* Stringify `mtime`

* Check if ESLint is running in Deno or Bun

Note: `isRunningInBun` and `isRunningInDeno` are functions to make treeshaking for consuming libraries easier.

* Try a different approach for loading TS config files

- This is done for mainly 2 reasons:

  1. We don't know how many runtime environments are going to support loading TS files natively in the future, so this saves us having to check for every single one.
  2. This also ensures that we give the user the option of passing their own TS loader of choice through `NODE_OPTIONS` in CLI for example: `NODE_OPTIONS=--import=tsx/esm`, without ESLint getting in the way and potentially causing conflicts between multiple loaders.

* Add tests for `lintFiles` with TS config files

* Revert "Try a different approach for loading TS config files"

This reverts commit 209c79169b681cebea35c7885233bbfdb1e861ae.

* Convert `Severity` type to a `const enum`

* Add tests for TS config files containing `const enum`s

* Add `ESLintNameSpace` local `namespace`

* Add tests for TS config files containing importing a local `namespace`

* Fix minor type issues in JSDocs

* Add tests for passing TS config files to `overrideConfigFile`

* Bump `jiti` to version 1.21.1

* Bump `jiti` to version 1.21.6

* Add basic docs for loading TypeScript configuration files

* Fix lint issues

* Bump `jiti` to version 2.0.0-beta.1

* Remove `esmResolve` as it has been removed in v2 of `jiti`

* Fix types for `createCustomTeardown`

* Remove `interopDefault: true`

- `interopDefault: true` does not work well with `jiti.import()`.

* Fix type of `eslint` in test file

* Fix lint issues in test file

* Add more tests

- Added tests for top-level `await`, interoperability, and mixed ESM/CJS syntax.

* Defer to v10 in docs

* Bump `jiti` to version 2.0.0-beta.3

* Fix import of `jiti`

* Fix `jiti` link in docs

* Fix `jiti` link in docs

* Add `unstable_ts_config` to `activeFlags`

* Fix issues in `configuration-files.md`

* Fix `LintResults` in `eslint.js`

* Change `LintResults` to `LintResult` in `eslint.js`

* Remove warning regarding top-level `await`

* Explicitly check for `.ts`, `.mts` or `.cts` extensions

* Check if `"unstable_ts_config"` flag is enabled

* Fix import and export assignment tests

* Fix remaining issues in `configuration-files.md`

* Fix test title

* De-duplicate test

* Revert "Fix broken unit tests caused by stubbed `process.version`"

This reverts commit f339591ce3606a1c63fac63eb93a34427e787cc5.

* Remove unnecessary checks for `"unstable_ts_config"` flag

* Fix type of `findConfigFile`

* Make sure tests fail when the correct config file is not loaded

* Add a test for `"unstable_ts_config"`

- Added a test to check that the TS config file is not loaded when the `"unstable_ts_config"` flag is not set.

* Remove fallback to `default` when loading `jiti.createJiti`

* Update `configuration-files.md`

* Update description of `"unstable_ts_config"` flag

* Add comment explaining purpose of `helper.ts`

* Disable `moduleCache`

* Add test to check reloading logic for TS config files

* Add comment for disabling `moduleCache`

* Rework `hasUnstableTSConfigFlag` logic

* Fix unit tests

* Fallback to `default` when loading `jiti`

* Rework logic for loading TS config files

- Rework the logic to ensure `overrideConfigFile` does not load TS config files unless the `unstable_ts_config` flag is set.

* Remove default value for `hasUnstableTSConfigFlag` parameter

* Remove type assertion

* Remove unnecessary `process?.versions?.bun` check

* Remove unnecessary `LintResults` type

* Fix parameter type of `eslintWithPlugins`

- We avoid potential repetition by using the new [`@import JSDoc tags`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#the-jsdoc-import-tag) released in TypeScript 5.5.

* Add tests for loading TypeScript config files that export a promise

* Update `jiti` peer dependency to allow any version

* Warn about using an outdated version of `jiti`

* Fix minor issue in `configuration-files.md`

* Add section about `--flag` in `configuration-files.md`

* Reapply "Fix broken unit tests caused by stubbed `process.version`"

This reverts commit f369145e6579f93746839d0aff5b281c80bd5100.

* Switch to `jiti` v1 until `jiti` v2 becomes stable

* Add commented-out unit tests for `jiti` v2

* Throw a `TypeError` if `jiti.import` is not a function

* Change `TypeError` to `Error`

---------

Co-authored-by: Anthony Fu <anthonyfu117@hotmail.com>